name: Delete Branch Test
run-name: 🚿 ${{ github.actor }} 🚀

on:
  workflow_dispatch:

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use script
        id: deletion
        run: |
          chmod +x ./scripts/branchCleanup.sh
          ./scripts/branchCleanup.sh
