name: Delete Bracnh Test
run-name: 🚿 ${{ github.actor }} 🚀

on:
  workflow_dispatch:

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: use script
        id: deletion
        run: |
          ./scripts/branchCleanup.sh
