name: Delete Branch Test
run-name: 🚿 ${{ github.actor }} 🚀

on:
  workflow_dispatch:

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use script
        id: deletion
        run: |
          chmod +x ./scripts/branchCleanup.sh
          ./scripts/branchCleanup.sh

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: debug-logs
          path: |
            step*.log
