name: Slack Notification
on:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      status:
        required: true
        type: string
      slack-message-ts:
        required: true
        type: string
      slack-channel-id:
        required: true
        type: string
    secrets:
      ACTIONS_SLACK_BOT_TOKEN:
        required: true

jobs:
  notify-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ inputs.slack-channel-id }}
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ inputs.status == 'success' && '#36a64f' || '#ff0000' }}",
                  "text": "${{ inputs.status == 'success' && '✅' || '🚨' }} ${{ inputs.job-name }} ${{ inputs.status }}"
                }
              ],
              "thread_ts": "${{ inputs.slack-message-ts }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.ACTIONS_SLACK_BOT_TOKEN }}
